
[versions]
koin-version = "4.0.0"
kotlin-version = "2.0.21"
ktor-version = "3.0.1"
logback-version = "1.4.14"
mongo-version = "4.10.2"
kvision-version = "8.0.1"

[libraries]
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin-version" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin-version" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor-version" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor-version" }
mongodb-driver-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "mongo-version" }
mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongo-version" }
bson = { module = "org.mongodb:bson", version.ref = "mongo-version" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder-jvm", version.ref = "ktor-version" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth-jvm", version.ref = "ktor-version" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt-jvm", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml-jvm", version.ref = "ktor-version" }
kotlin-stdlib-js = { module = "org.jetbrains.kotlin:kotlin-stdlib-js", version.ref = "kotlin-version" }
kvision-kvision = { module = "io.kvision:kvision", version.ref = "kvision-version" }
kvision-bootstrap = { module = "io.kvision:kvision-bootstrap", version.ref = "kvision-version" }
kvision-ktor-koin = { module = "io.kvision:kvision-server-ktor-koin", version.ref = "kvision-version" }
kvision-state = { module = "io.kvision:kvision-state", version.ref = "kvision-version" }
kvision-fontawesome = { module = "io.kvision:kvision-fontawesome", version.ref = "kvision-version" }
kvision-i18n = { module = "io.kvision:kvision-i18n", version.ref = "kvision-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor-version" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }

[plugins]
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.0.21" }
kvision = { id = "io.kvision", version = "8.0.1" }
